import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPage, type LegalSection } from '@/components/LegalPage';

export const metadata: Metadata = {
  title: 'Terms of service',
  description: 'The terms for using Orbitdesk during its invite-only beta.',
};

const sections: LegalSection[] = [
  {
    id: 'the-service',
    title: 'The service',
    body: (
      <>
        <p>
          Orbitdesk is an open-source web application that connects to Google accounts you authorise and shows their
          mail, calendars and tasks in one place, with an assistant that can prepare actions for your approval.
        </p>
        <p>
          It is currently an invite-only beta. Features may change, and during Google’s testing mode a linked account has
          to be reconnected every seven days.
        </p>
      </>
    ),
  },
  {
    id: 'your-accounts',
    title: 'Your accounts',
    body: (
      <ul>
        <li>Only connect Google accounts you own or are authorised to use.</li>
        <li>
          If an account belongs to an organisation, its administrator may restrict what Orbitdesk can access. Those
          restrictions are shown rather than worked around.
        </li>
        <li>You are responsible for keeping your Google sign-in secure and for activity carried out from your session.</li>
      </ul>
    ),
  },
  {
    id: 'approvals',
    title: 'Actions and approvals',
    body: (
      <>
        <p>
          Sending a message, creating or cancelling an event, or deleting something from the interface is your own
          action. When the assistant or an automation proposes such an action, it is carried out only after you approve
          the exact content shown.
        </p>
        <ul>
          <li>An approval applies to the recipients, account, content and time you saw. If any of those change, the action is paused for a new decision.</li>
          <li>A scheduled action can be cancelled until it starts. A message Google has accepted cannot be recalled.</li>
          <li>If the outcome of a send is uncertain, Orbitdesk asks you to review it instead of sending again.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'assistant-output',
    title: 'Assistant output',
    body: (
      <p>
        The assistant’s answers and drafts are generated by a language model and can be wrong or incomplete. Check the
        sources it links and read drafts before approving them. You remain responsible for what is sent from your
        accounts.
      </p>
    ),
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable use',
    body: (
      <ul>
        <li>Do not use Orbitdesk for bulk or unsolicited email, or to evade Google’s sending limits.</li>
        <li>Do not attempt to access another person’s workspace, data or credentials.</li>
        <li>Do not use it to break the law or Google’s terms for the connected products.</li>
        <li>Usage limits apply to connected accounts, automation frequency and assistant requests, and are enforced by the server.</li>
      </ul>
    ),
  },
  {
    id: 'sandbox',
    title: 'The sandbox demo',
    body: (
      <p>
        The demo uses simulated accounts and data. It delivers nothing and may be reset or removed at any time. Do not
        enter real confidential information into it.
      </p>
    ),
  },
  {
    id: 'open-source',
    title: 'Open-source software',
    body: (
      <p>
        Orbitdesk’s source code is available under its open-source licence, which governs your rights to the software
        itself. These terms cover use of a hosted Orbitdesk service. If you run your own deployment, you are its
        operator and are responsible for its configuration, its Google Cloud project and its data.
      </p>
    ),
  },
  {
    id: 'availability',
    title: 'Availability and warranty',
    body: (
      <p>
        The service is provided as is during the beta, without a guarantee of availability or fitness for a particular
        purpose. It depends on Google’s APIs and on a model provider, either of which may be unavailable or rate
        limited. To the extent permitted by law, liability for indirect or consequential loss is excluded.
      </p>
    ),
  },
  {
    id: 'ending',
    title: 'Ending your use',
    body: (
      <p>
        You can stop at any time by disconnecting your accounts or deleting your Orbitdesk account from Connections
        &amp; settings. Access may be suspended for misuse or to protect the service. How data is handled when you
        leave is described in the <Link href="/privacy">privacy policy</Link>.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      kicker="Terms"
      title="Terms of service"
      updated="October 4, 2026"
      sections={sections}
      intro={
        <p>
          These terms are short on purpose. They describe what Orbitdesk does for you, what stays your responsibility,
          and the limits of a beta product that acts on real mailboxes.
        </p>
      }
    />
  );
}
