import '../packages/core/src/config';
import { beforeAll, afterAll, describe, expect, it, vi } from 'vitest';
import { handle, bootstrap } from '../packages/core/src/http';
import { db, json, object } from '../packages/core/src/db';
import { createDemo } from '../packages/core/src/seed';
import { createSession } from '../packages/core/src/session';
import { resources, connection, type Context } from '../packages/core/src/store';
import { propose, approve, execute, prepareSend } from '../packages/core/src/actions';
import { stopQueue, tick, nextRun } from '../packages/core/src/jobs';
import { availability, createDraft } from '../packages/core/src/workspace';
import { encrypt, decrypt, safeHtml, hashPayload } from '../packages/core/src/security';
import { syncMail } from '../packages/core/src/google';
import { readDocument } from '../packages/core/src/documents';

let one:Context,two:Context,cookie:string,foreignCookie:string;
async function call(path:string,method='GET',data?:unknown,auth=cookie,origin='http://localhost:3100'){const r=await handle(new Request('http://localhost:3100/api/'+path,{method,headers:{cookie:auth,origin,'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)}));return {status:r.status,json:await r.json()};}
beforeAll(async()=>{one=await createDemo();two=await createDemo();cookie=(await createSession(one.user.id,true)).split(';')[0];foreignCookie=(await createSession(two.user.id,true)).split(';')[0];});
afterAll(async()=>{vi.unstubAllGlobals();await stopQueue();await db.user.deleteMany({where:{id:{in:[one?.user.id,two?.user.id].filter(Boolean)}}});await db.$disconnect();});

describe('workspace isolation and API',()=>{
  it('returns no private data without a session and rejects cross-site writes',async()=>{expect((await call('bootstrap','GET',undefined,'')).status).toBe(401);expect((await call('auth/demo','POST',{},'','https://attacker.example')).status).toBe(403);expect((await call('session','GET',undefined,'')).json.data.session).toBeNull();});
  it('provides contract-shaped bootstrap with twelve accounts and eight calendars',async()=>{const r=await call('bootstrap');expect(r.status).toBe(200);expect(r.json.data.session.mode).toBe('demo');expect(r.json.data.connections).toHaveLength(12);expect(r.json.data.calendars).toHaveLength(8);expect(r.json.data.settings.workingHours.start).toBe('09:00');expect(JSON.stringify(r.json)).not.toContain('credentials');});
  it('blocks cross-workspace ids for threads, tasks and account selection',async()=>{const threads=await resources(one,'thread'),tasks=await resources(one,'task');expect((await call('threads/'+threads[0].id,'GET',undefined,foreignCookie)).status).toBe(404);expect((await call('tasks/'+tasks[0].id,'PATCH',{completed:true},foreignCookie)).status).toBe(404);expect((await call('threads?accountId='+threads[0].connectionId,'GET',undefined,foreignCookie)).status).toBe(404);});
  it('validates mutations and can create, complete and delete tasks',async()=>{const b=await bootstrap(one),taskListId=b.taskLists[0].id;expect((await call('tasks','POST',{taskListId,title:''})).status).toBe(422);const made=await call('tasks','POST',{taskListId,title:'Integration check',due:'2026-10-05'});expect(made.status).toBe(201);const done=await call('tasks/'+made.json.data.id,'PATCH',{completed:true});expect(done.json.data.completed).toBe(true);expect((await call('tasks/'+made.json.data.id,'DELETE')).status).toBe(200);});
  it('archives and restores a thread through actual endpoints',async()=>{const r=(await resources(one,'thread'))[0];let out=await call('threads/'+r.id+'/actions','POST',{action:'archive'});expect(out.json.data.inInbox).toBe(false);out=await call('threads/'+r.id+'/actions','POST',{action:'unarchive'});expect(out.json.data.inInbox).toBe(true);});
});
describe('drafts and immutable approvals',()=>{
  it('prevents replying from a different account',async()=>{const threads=await resources(one,'thread'),b=await bootstrap(one);const other=b.connections.find(c=>c.id!==threads[0].connectionId)!;expect((await call('drafts','POST',{accountId:other.id,mode:'reply',threadId:threads[0].id,to:[{email:'person@example.com'}],subject:'Re: Test',bodyText:'Hello'})).status).toBe(422);});
  it('binds replies to a MIME snapshot, rejects stale edits and detects changed approvals',async()=>{const t=(await resources(one,'thread'))[0],c=await connection(one,t.connectionId);const d=await createDraft(one,{accountId:c.id,mode:'reply',threadId:t.id,to:[{email:'reply@example.com'}],subject:'Re: '+object(t.data).subject,bodyText:'Reviewed, thank you.'});const raw=object((await db.resource.findUnique({where:{id:d.id}}))!.data)._raw as string;expect(Buffer.from(raw,'base64url').toString()).toMatch(/In-Reply-To:/i);const prepared=await prepareSend(one,d.id,{version:d.version,intent:'preview'});expect((await call('actions/'+prepared.action.id+'/approve','POST',{contentHash:'wrong'})).status).toBe(409);const edit=await call('drafts/'+d.id,'PATCH',{version:d.version,bodyText:'Updated body.'});expect(edit.status).toBe(200);expect((await call('drafts/'+d.id,'PATCH',{version:d.version,bodyText:'Stale edit'})).status).toBe(409);expect((await call('actions/'+prepared.action.id+'/approve','POST',{contentHash:prepared.action.contentHash})).status).toBe(409);});
  it('approves exactly once and cannot replay an executed action',async()=>{const list=(await resources(one,'taskList'))[0];const a=await propose(one,'create_task',{taskListId:list.id,title:'Approved once'},{origin:'agent'});const results=await Promise.allSettled([approve(one,a.id,a.payloadHash),approve(one,a.id,a.payloadHash)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);await execute(a.id);const stored=(await db.action.findUnique({where:{id:a.id}}))!;expect(stored.status).toBe('succeeded');expect(stored.attempts).toBe(1);expect((await resources(one,'task')).filter(t=>object(t.data).title==='Approved once')).toHaveLength(1);});
  it('simulates send through a real action and consumes the sandbox draft',async()=>{const c=(await bootstrap(one)).connections[0];const d=await createDraft(one,{accountId:c.id,mode:'new',to:[{email:'safe@example.com'}],subject:'Sandbox send check',bodyText:'This is only in the isolated sandbox.'});const result=await prepareSend(one,d.id,{version:d.version,intent:'send'});expect(result.action.state).toBe('succeeded');expect(result.draft).toBeNull();expect(result.action.result?.message).toContain('sandbox');});
  it('survives scheduling without memory and marks abandoned execution uncertain',async()=>{const l=(await resources(one,'taskList'))[0],a=await propose(one,'create_task',{taskListId:l.id,title:'Durable scheduled task'});await db.action.update({where:{id:a.id},data:{status:'queued',approvedAt:new Date(),scheduledAt:new Date(Date.now()-1000)}});await tick();expect((await db.action.findUnique({where:{id:a.id}}))!.status).toBe('succeeded');const uncertain=await propose(one,'create_task',{taskListId:l.id,title:'Uncertain task'});await db.action.update({where:{id:uncertain.id},data:{status:'running',leaseUntil:new Date(Date.now()-1000)}});await tick();expect((await db.action.findUnique({where:{id:uncertain.id}}))!.status).toBe('needs_review');});
  it('preserves Bcc in Gmail MIME and binds a scheduled time to its approved payload',async()=>{const c=(await bootstrap(one)).connections[0],d=await createDraft(one,{accountId:c.id,mode:'new',to:[{email:'to@example.com'}],bcc:[{email:'hidden@example.com'}],subject:'MIME check',bodyText:'Text',addAttachments:[{filename:'note.txt',mimeType:'text/plain',dataBase64:Buffer.from('attachment').toString('base64')}]});const stored=(await db.resource.findUnique({where:{id:d.id}}))!;expect(Buffer.from(object(stored.data)._raw as string,'base64url').toString()).toContain('Bcc: hidden@example.com');const send=await prepareSend(one,d.id,{version:d.version,intent:'send',scheduleAt:new Date(Date.now()+3600000).toISOString()});expect(send.action.state).toBe('queued');const row=(await db.action.findUnique({where:{id:send.action.id}}))!;expect(object(object(row.payload).input).scheduleAt).toBe(send.action.scheduledAt);expect(row.payloadHash).toBe(hashPayload(row.payload));await call('actions/'+row.id+'/cancel','POST',{});});
  it('executes document edits only after approving their exact content',async()=>{const f=(await resources(one,'file')).find(r=>String(object(r.data).mimeType).includes('document'))!;const before=await readDocument(one,{fileId:f.id});const a=await propose(one,'other',{operation:'doc_append',fileId:f.id,text:'Approved document note.'});expect((await readDocument(one,{fileId:f.id})).content).toBe(before.content);await approve(one,a.id,a.payloadHash);expect(String((await readDocument(one,{fileId:f.id})).content)).toContain('Approved document note.');await expect(readDocument(two,{fileId:f.id})).rejects.toMatchObject({status:404});});
});
describe('calendar and security',()=>{
  it('checks busy intervals and timezone-aware slots across the DST boundary',async()=>{const cal=(await resources(one,'calendar'))[0];const v=await availability(one,{timeMin:'2026-10-25T00:00:00Z',timeMax:'2026-10-25T04:00:00Z',durationMinutes:30,calendarIds:[cal.id],withinWorkingHours:false,limit:20});expect(v.complete).toBe(true);expect(v.slots.length).toBeGreaterThan(0);for(const slot of v.slots)expect(Date.parse(slot.end)-Date.parse(slot.start)).toBe(30*60000);const next=nextRun({time:'08:30',days:[0],timezone:'Europe/Amsterdam'},new Date('2026-10-24T12:00:00Z'));expect(next.toISOString()).toBe('2026-10-25T07:30:00.000Z');});
  it('requires exclusive all-day end dates and protects calendar versions',async()=>{const cal=(await resources(one,'calendar'))[0];expect((await call('events','POST',{calendarId:cal.id,title:'Invalid',allDay:true,start:'2026-10-04',end:'2026-10-04'})).status).toBe(422);const made=await call('events','POST',{calendarId:cal.id,title:'All-day test',allDay:true,start:'2026-10-04',end:'2026-10-05'});expect(made.status).toBe(201);expect(made.json.data.canEdit).toBe(true);expect((await call('events/'+made.json.data.id,'PATCH',{title:'Changed',version:'stale'})).status).toBe(409);expect((await call('events/'+made.json.data.id,'DELETE')).status).toBe(200);});
  it('authenticates encryption and strips script, remote images and unsafe URLs',()=>{const cipher=encrypt({refresh_token:'test-secret'});expect(decrypt(cipher)).toEqual({refresh_token:'test-secret'});expect(()=>decrypt(cipher.slice(0,-3)+'abc')).toThrow();const html=safeHtml('<script>alert(1)</script><img src="https://tracking.example"><a href="javascript:alert(1)">x</a><b>safe</b>');expect(html).not.toContain('script');expect(html).not.toContain('<img');expect(html).not.toContain('javascript');expect(html).toContain('<b>safe</b>');expect(hashPayload({b:2,a:1})).toBe(hashPayload({a:1,b:2}));});
});
describe('Google sync contracts',()=>{
  it('keeps Gmail history ids as strings, reads every page and never commits a failed cursor',async()=>{let c=await connection(one,(await resources(one,'thread'))[0].connectionId);c=await db.connection.update({where:{id:c.id},data:{credentials:encrypt({access_token:'test-access',expiry_date:Date.now()+3600000}),scopes:['https://www.googleapis.com/auth/gmail.modify'],syncState:json({mailHistoryId:'9007199254740993000'})}});const calls:string[]=[];const mock=vi.fn(async(url:any)=>{calls.push(String(url));let data:any={};if(String(url).endsWith('/profile'))data={historyId:'9007199254740993009'};else if(String(url).includes('/history?'))data=String(url).includes('pageToken=next')?{history:[],historyId:'9007199254740993009'}:{history:[],nextPageToken:'next',historyId:'9007199254740993001'};else if(String(url).includes('/labels'))data={labels:[]};else if(String(url).includes('/drafts'))data={drafts:[]};else if(String(url).includes('sendAs'))data={sendAs:[]};return Response.json(data);});vi.stubGlobal('fetch',mock);const delta=await syncMail(c);expect(delta.mailHistoryId).toBe('9007199254740993009');expect(calls.some(x=>x.includes('startHistoryId=9007199254740993000'))).toBe(true);expect(calls.some(x=>x.includes('pageToken=next'))).toBe(true);expect(object((await db.connection.findUnique({where:{id:c.id}}))!.syncState).mailHistoryId).toBe('9007199254740993000');mock.mockImplementationOnce(async()=>{throw new Error('network failed');});await expect(syncMail(c)).rejects.toThrow();vi.unstubAllGlobals();await db.connection.update({where:{id:c.id},data:{credentials:null,scopes:['sandbox']}});});
});
