import type { Connection as DBConnection, Resource, Action as DBAction, Automation as DBAutomation, AgentMessage as DBMessage } from '@prisma/client';
import type * as T from './types';
import { object } from './db';
import type { Context } from './store';
import { GOOGLE_SCOPES } from './google';

const iso=(d:Date|string|null|undefined)=>d?new Date(d).toISOString():null;
export function sessionView(ctx:Context):T.Session {return {mode:ctx.workspace.demo?'demo':'real',user:{id:ctx.user.id,name:ctx.user.name,email:ctx.user.email,avatarUrl:ctx.user.avatarUrl},workspaceId:ctx.workspace.id,createdAt:iso(ctx.workspace.createdAt)!,expiresAt:null};}
export function settingsView(ctx:Context):T.Settings {
  const v=object(ctx.workspace.settings);const wh=object(v.workingHours);
  return {timezone:String(v.timezone||'Europe/Amsterdam'),weekStartsOn:v.weekStartsOn===0?0:1,workingHours:{days:wh.days as number[]||[1,2,3,4,5],start:typeof wh.start==='string'?wh.start:'09:00',end:typeof wh.end==='string'?wh.end:'17:00'},meetingBufferMinutes:Number(v.meetingBufferMinutes||0),defaultMeetingMinutes:Number(v.defaultMeetingMinutes||30),defaultAccountId:v.defaultAccountId as string||null,defaultCalendarId:v.defaultCalendarId as string||null,defaultTaskListId:v.defaultTaskListId as string||null,loadRemoteImages:!!v.loadRemoteImages,contactLookup:!!v.contactLookup};
}
export function connectionView(c:DBConnection,ctx:Context):T.Connection {
  const s=object(c.settings),state=object(c.syncState);const demo=!c.credentials&&ctx.workspace.demo;
  return {id:c.id,email:c.email,name:c.name,avatarUrl:s.avatarUrl as string||null,label:c.label,group:s.group as T.ConnectionGroup||'other',color:c.color,kind:c.email.endsWith('@gmail.com')?'consumer':'workspace',demo,isLogin:c.googleSub===ctx.user.googleSub,status:({connected:'active'}[c.status]||c.status) as T.ConnectionStatus,statusDetail:c.error,lastSyncAt:iso(c.lastSyncAt),sync:(['mail','calendar','tasks'] as const).map(resource=>({resource,status:c.status==='syncing'?'syncing':object(state[resource]).error?'error':object(state[resource]).lastSuccessAt||c.lastSyncAt?'ok':'never',lastSuccessAt:object(state[resource]).lastSuccessAt as string||iso(c.lastSyncAt),error:object(state[resource]).error as string||null})),permissions:(['mail','calendar','tasks','contacts','files'] as const).map(resource=>{const scopes=GOOGLE_SCOPES[resource].filter(x=>c.scopes.includes(x));return {resource,state:demo||scopes.length?'granted':'not_requested',scopes,detail:demo?'Simulated in this sandbox':scopes.length?null:'Connect again to grant access.'};}),assistantAccess:s.assistantAccess!==false&&s.assistantEnabled!==false,signature:s.signature as string||null,writingPreferences:s.writingPreferences as string||null,sendAs:s.sendAs as T.SendAsIdentity[]||[{email:c.email,name:c.name,isDefault:true}],createdAt:iso(c.createdAt)!};
}
export function calendarView(r:Resource):T.Calendar {const d=object(r.data);return {id:r.id,accountId:r.connectionId,name:String(d.name||d.summary||'Calendar'),color:String(d.color||'#7287ad'),timezone:String(d.timezone||d.timeZone||'UTC'),accessRole:(d.accessRole||'reader') as T.CalendarAccessRole,primary:!!d.primary,visible:d.visible!==false,includeInAvailability:d.includeInAvailability!==false,error:d.error as string||null};}
export function threadView(r:Resource):T.ThreadSummary {
  const d=object(r.data),messages=(d.messages||[]) as any[],labels=(d.labels||[]) as string[];
  return {id:r.id,accountId:r.connectionId,subject:String(d.subject||''),snippet:String(d.snippet||''),participants:d.participants as T.Address[]||[],messageCount:Number(d.messageCount||messages.length),unread:!!d.unread,starred:!!d.starred,hasAttachments:messages.some(m=>m.attachments?.length),hasDraft:!!d.hasDraft,inInbox:d.inInbox as boolean??labels.includes('INBOX'),trashed:!!d.trashed||labels.includes('TRASH'),labelIds:labels,lastMessageAt:String(d.lastMessageAt||r.updatedAt.toISOString())};
}
export function messageView(m:any,r:Resource):T.Message {
  return {id:m.id,threadId:r.id,accountId:r.connectionId,from:m.from||{name:null,email:''},to:m.to||[],cc:m.cc||[],bcc:m.bcc||[],replyTo:m.replyTo||[],subject:m.subject||'',sentAt:m.sentAt||m.date||r.updatedAt.toISOString(),snippet:m.snippet||'',bodyText:m.bodyText||m.body||null,bodyHtml:m.bodyHtml||null,attachments:(m.attachments||[]).map((a:any)=>({id:a.id,filename:a.filename,mimeType:a.mimeType,size:a.size,inline:!!a.inline,downloadUrl:a.attachmentId||a.dataBase64?`/api/attachments/${r.id}/${encodeURIComponent(m.id)}/${encodeURIComponent(a.id)}`:null})),unread:!!m.unread,starred:!!m.starred,outgoing:!!m.outgoing};
}
export function threadDetailView(r:Resource):T.ThreadDetail {const d=object(r.data);return {...threadView(r),messages:((d.messages||[]) as any[]).map(m=>messageView(m,r)),url:d.url as string||null};}
export function draftView(r:Resource):T.Draft {const d=object(r.data);return {id:r.id,accountId:r.connectionId,mode:(d.mode||'new') as T.DraftMode,threadId:d.threadId as string||null,inReplyToMessageId:d.inReplyToMessageId as string||null,from:d.from as T.Address,to:d.to as T.Address[]||[],cc:d.cc as T.Address[]||[],bcc:d.bcc as T.Address[]||[],subject:String(d.subject||''),bodyText:String(d.bodyText||''),bodyHtml:d.bodyHtml as string||null,attachments:((d.attachments||[]) as any[]).map(a=>({id:a.id,filename:a.filename,mimeType:a.mimeType,size:a.size,inline:!!a.inline,downloadUrl:a.dataBase64?`/api/attachments/${r.id}/draft/${a.id}`:null})),status:(d.status||'draft') as T.DraftStatus,scheduledAt:d.scheduledAt as string||null,actionId:d.actionId as string||null,version:r.version||r.updatedAt.toISOString(),createdAt:iso(r.createdAt)!,updatedAt:iso(r.updatedAt)!};}
export function eventView(r:Resource):T.CalendarEvent {const d=object(r.data);return {id:r.id,calendarId:r.parentId||String(d.calendarId),accountId:r.connectionId,title:String(d.title||d.summary||''),description:d.description as string||null,location:d.location as string||null,allDay:!!d.allDay,start:String(d.start),end:String(d.end),timezone:d.timezone as string||d.timeZone as string||null,status:(d.status||'confirmed') as T.CalendarEvent['status'],busy:d.busy!==false,organizer:d.organizer as T.Address||null,attendees:d.attendees as T.Attendee[]||[],myResponse:d.myResponse as T.ResponseStatus||null,canEdit:d.canEdit as boolean??!!d.isOrganizer,canRsvp:!!d.canRsvp,recurrence:d.recurrence as string[]||null,recurringEventId:d.recurringEventId as string||null,meetUrl:d.meetUrl as string||d.meetLink as string||null,url:d.url as string||null,reminderMinutes:d.reminderMinutes as number[]||[],version:r.version||r.updatedAt.toISOString(),updatedAt:iso(r.updatedAt)!};}
export function taskView(r:Resource):T.Task {const d=object(r.data);return {id:r.id,taskListId:r.parentId||String(d.taskListId||d.listId),accountId:r.connectionId,title:String(d.title),notes:d.notes as string||null,due:d.due as string||d.dueDate as string||null,completed:!!d.completed||d.status==='completed',completedAt:d.completedAt as string||null,parentId:d.parentId as string||null,position:String(d.position||''),source:d.source as T.SourceRef||null,reminderAt:d.reminderAt as string||null,assigned:!!d.assigned,url:d.url as string||null,updatedAt:iso(r.updatedAt)!};}
export function taskListView(r:Resource,tasks:Resource[]=[]):T.TaskList {const d=object(r.data);return {id:r.id,accountId:r.connectionId,title:String(d.title||d.name||'Tasks'),isDefault:!!d.isDefault,openCount:tasks.filter(t=>t.parentId===r.id&&!taskView(t).completed).length,updatedAt:iso(r.updatedAt)!};}
export function fileView(r:Resource):T.DriveFile {const d=object(r.data),mime=String(d.mimeType||'');let kind:T.FileKind='other';if(mime.includes('document'))kind='doc';else if(mime.includes('spreadsheet'))kind='sheet';else if(mime.includes('presentation'))kind='slides';else if(mime.includes('folder'))kind='folder';else if(mime.includes('pdf'))kind='pdf';else if(mime.startsWith('image/'))kind='image';return {id:r.id,accountId:r.connectionId,name:String(d.name||''),kind,mimeType:mime,owner:d.owner as T.Address||null,shared:!!d.shared,size:d.size?Number(d.size):null,modifiedAt:String(d.modifiedTime||r.updatedAt.toISOString()),url:d.webViewLink as string||null};}
export function actionView(a:DBAction):T.Action {const p=object(a.payload),result=object(a.result);return {id:a.id,kind:a.type as T.ActionKind,state:a.status as T.ActionState,title:a.title,summary:a.description,accountId:a.connectionId,origin:a.source as T.Action['origin'],preview:p.preview as T.ActionPreview,contentHash:a.payloadHash,scheduledAt:iso(a.scheduledAt),steps:[{id:a.id,label:a.title,state:a.status==='succeeded'?'succeeded':a.status==='failed'?'failed':a.status==='running'?'running':'pending',detail:a.error,url:result.url as string||null}],result:a.result?{message:result.message as string||'Completed',url:result.url as string||null}:null,error:a.error?{code:a.status==='needs_review'?'conflict':'provider_error',message:a.error}:null,conversationId:p.conversationId as string||null,automationId:p.automationId as string||null,createdAt:iso(a.createdAt)!,updatedAt:iso(a.updatedAt)!,decidedAt:iso(a.approvedAt),completedAt:iso(a.completedAt)};}
export function automationView(a:DBAutomation):T.Automation {const c=object(a.config);return {id:a.id,template:(a.type==='morning_brief'?'daily_brief':a.type) as T.AutomationTemplate,name:a.name,enabled:a.enabled,accountIds:c.accountIds as string[]||[],schedule:c.schedule as T.AutomationSchedule||{time:'08:30',days:[1,2,3,4,5],timezone:'Europe/Amsterdam'},config:c.config as T.AutomationConfig||{},lastRunAt:iso(a.lastRunAt),lastRunStatus:a.lastRunAt?a.lastError?'failed':'ok':null,lastRunDetail:a.lastError||c.lastRunDetail as string||null,nextRunAt:iso(a.nextRunAt),createdAt:iso(a.createdAt)!,updatedAt:iso(a.createdAt)!};}
export function sourceView(r:Resource):T.SourceRef {const d=object(r.data);return {kind:r.kind as T.SourceRef['kind'],id:r.id,accountId:r.connectionId,title:String(d.subject||d.title||d.name||'Resource'),snippet:String(d.snippet||d.notes||'').slice(0,240)||null,url:d.url as string||d.webViewLink as string||null,occurredAt:d.lastMessageAt as string||d.start as string||null};}
export function messageRecordView(m:DBMessage,actions:DBAction[]=[]):T.AgentMessage {const meta=object(m.metadata);return {id:m.id,conversationId:m.conversationId,role:m.role as 'user'|'assistant',text:m.content,accountIds:meta.accountIds as string[]||[],tools:meta.tools as T.ToolCall[]||[],sources:meta.sources as T.SourceRef[]||[],actions:actions.map(actionView),model:meta.model as string||null,createdAt:iso(m.createdAt)!};}
