import { randomUUID } from 'node:crypto';
import nodemailer from 'nodemailer';
import { formatInTimeZone, fromZonedTime } from 'date-fns-tz';
import type { Connection, Resource } from '@prisma/client';
import { db, json, object } from './db';
import { type Context, connection, connections, resource, resources, put, activity } from './store';
import { api, enc, pages, hydrateThread, hydrateDraft, fetchEvents, eventData, GOOGLE_SCOPES } from './google';
import { AppError, sha256, hashPayload } from './security';
import * as V from './validation';
import * as views from './views';
import type * as T from './types';
import { matchesMailQuery } from './mail-search';

export const list=<X>(items:X[],gaps:T.SourceGap[]=[]):T.ListResult<X>=>({items,nextCursor:null,gaps});
export function scopeAvailable(c:Connection,area:string,ctx:Context) {return ctx.workspace.demo||(area==='files'?GOOGLE_SCOPES.files.slice(0,2).some(s=>c.scopes.includes(s)):c.scopes.includes(GOOGLE_SCOPES[area]?.[0]||''));}
export function assertScope(c:Connection,area:string,ctx:Context) {if(!scopeAvailable(c,area,ctx))throw new AppError('permission_missing',`Connect this account again to grant ${area} access.`,403);if(c.status==='paused')throw new AppError('permission_missing','This account is paused.',403);}
export async function gapList(ctx:Context,area:T.ResourceKind):Promise<T.SourceGap[]> {
  return (await connections(ctx)).flatMap(c=>{
    const error=object(object(c.syncState)[area]).error;
    let code:T.ErrorCode,message:string;
    if(!scopeAvailable(c,area,ctx)){code='permission_missing';message=`This account has no ${area} access.`;}
    else if(c.status==='reconnect_required'){code='reconnect_required';message=c.error||'Reconnect this Google account.';}
    else if(c.status==='paused'){code='permission_missing';message='This account is paused.';}
    else if(typeof error==='string'&&error){code='provider_error';message=error;}
    else return [];
    return [{accountId:c.id,resource:area,resourceId:null,code,message}];
  });
}
export async function getThreads(ctx:Context,q='',folder='inbox',labelId?:string) {
  const gaps=await gapList(ctx,'mail');
  const matching=new Set<string>();
  if(q&&!ctx.workspace.demo){
    const cachedKeys=new Set((await resources(ctx,'thread')).map(r=>`${r.connectionId}:${r.providerId}`));
    for(const c of await connections(ctx)){
      if(!scopeAvailable(c,'mail',ctx))continue;
      try{
        const matches=await pages(c,`gmail/threads?q=${enc(q)}&maxResults=100`,'threads');
        for(const m of matches)matching.add(`${c.id}:${m.id}`);
        // Google decides query membership. Reuse synced previews; opening a thread
        // still fetches its current full conversation. Only older cache misses need reads.
        const missing=matches.slice(0,100).filter(m=>!cachedKeys.has(`${c.id}:${m.id}`));
        for(let i=0;i<missing.length;i+=4)await Promise.all(missing.slice(i,i+4).map(m=>hydrateThread(c,m.id)));
      }catch(e){gaps.push({accountId:c.id,resource:'mail',resourceId:null,code:'provider_error',message:(e as Error).message});}
    }
  }
  const cached=await resources(ctx,'thread');let rows=cached.map(views.threadView);const bad=new Set(gaps.map(g=>g.accountId));rows=rows.filter(t=>!bad.has(t.accountId));
  rows=rows.filter(t=>folder==='trash'?t.trashed:!t.trashed&& (folder==='inbox'?t.inInbox:folder==='unread'?t.inInbox&&t.unread:folder==='starred'?t.starred:folder==='sent'?t.labelIds.includes('SENT'):true));
  if(labelId)rows=rows.filter(t=>t.labelIds.includes(labelId));
  if(q){if(ctx.workspace.demo)rows=rows.filter(t=>matchesMailQuery(views.threadDetailView(cached.find(r=>r.id===t.id)!),q));else{const selected=new Set(cached.filter(r=>matching.has(`${r.connectionId}:${r.providerId}`)).map(r=>r.id));rows=rows.filter(t=>selected.has(t.id));}}
  rows.sort((a,b)=>b.lastMessageAt.localeCompare(a.lastMessageAt));return list(rows,gaps);
}
export async function getThread(ctx:Context,id:string) {let r=await resource(ctx,id,'thread');const c=await connection(ctx,r.connectionId);assertScope(c,'mail',ctx);if(!ctx.workspace.demo)r=await hydrateThread(c,r.providerId);return views.threadDetailView(r);}
export async function modifyThread(ctx:Context,id:string,input:unknown) {
  const v=V.threadAction.parse(input),r=await resource(ctx,id,'thread'),c=await connection(ctx,r.connectionId);assertScope(c,'mail',ctx);const d=object(r.data),labels=new Set<string>(d.labels as string[]||[]);
  const changes:Record<string,[string[],string[]]>={archive:[[],['INBOX']],unarchive:[['INBOX'],[]],mark_read:[[],['UNREAD']],mark_unread:[['UNREAD'],[]],star:[['STARRED'],[]],unstar:[[],['STARRED']],trash:[['TRASH'],['INBOX']],restore:[['INBOX'],['TRASH']]};
  let [add,remove]=changes[v.action]||[v.addLabelIds||[],v.removeLabelIds||[]];
  if(v.action==='label'){if(!add.length&&!remove.length)throw new AppError('validation_failed','Choose a label to add or remove.',422);const valid=await resources(ctx,'label',c.id);for(const label of [...add,...remove])if(!valid.some(l=>l.providerId===label))throw new AppError('validation_failed','Label does not belong to this account.',422);}
  if(v.messageId&&!((d.messages||[]) as any[]).some(m=>m.id===v.messageId))throw new AppError('not_found','Message not found in this thread.',404);
  if(!ctx.workspace.demo){if(v.action==='trash'||v.action==='restore')await api(c,`gmail/threads/${enc(r.providerId)}/${v.action==='trash'?'trash':'untrash'}`,{method:'POST'});else await api(c,`gmail/${v.messageId?'messages/'+enc(v.messageId):'threads/'+enc(r.providerId)}/modify`,{method:'POST',body:JSON.stringify({addLabelIds:add,removeLabelIds:remove})});return views.threadView(await hydrateThread(c,r.providerId));}
  add.forEach(x=>labels.add(x));remove.forEach(x=>labels.delete(x));const saved=await put(c,'thread',r.providerId,{...d,labels:[...labels],unread:labels.has('UNREAD'),starred:labels.has('STARRED'),inInbox:labels.has('INBOX'),trashed:labels.has('TRASH')},undefined,randomUUID());await activity(ctx,'mail.'+v.action,`${v.action.replaceAll('_',' ')}: ${d.subject}`,{},c.id,r.id);return views.threadView(saved);
}
async function mime(conn:Connection,d:any) {
  const transport=nodemailer.createTransport({streamTransport:true,buffer:true,newline:'unix'});
  const addr=(a:any)=>({name:a.name||'',address:a.email});
  const result=await transport.sendMail({from:addr(d.from),to:d.to.map(addr),cc:d.cc.map(addr),bcc:d.bcc.map(addr),subject:d.subject,text:d.bodyText,html:d.bodyHtml||undefined,messageId:d._messageId||`<${randomUUID()}@orbitdesk.app>`,inReplyTo:d._inReplyTo||undefined,references:d._references||undefined,attachments:(d.attachments||[]).map((a:any)=>({filename:a.filename,content:Buffer.from(a.dataBase64,'base64'),contentType:a.mimeType}))});return (result.message as Buffer).toString('base64url');
}
async function draftData(ctx:Context,c:Connection,v:any,prior:any={}) {
  const identities=views.connectionView(c,ctx).sendAs;const fromEmail=v.fromEmail||prior.from?.email||identities.find(a=>a.isDefault)?.email||c.email;
  if(!identities.some(a=>a.email.toLowerCase()===fromEmail.toLowerCase()))throw new AppError('validation_failed','Choose a verified sending identity for this account.',422);
  let attachments=[...(prior.attachments||[])].filter((a:any)=>!(v.removeAttachmentIds||[]).includes(a.id));attachments.push(...(v.addAttachments||[]).map((a:any)=>({...a,id:randomUUID(),size:Buffer.byteLength(a.dataBase64,'base64'),inline:false})));
  if(attachments.reduce((n,a)=>n+a.size,0)>10_000_000)throw new AppError('too_large','Attachments are limited to 10 MB per message.',413);
  const d={...prior,...v,from:{email:fromEmail,name:identities.find(a=>a.email===fromEmail)?.name||c.name},to:v.to||prior.to||[],cc:v.cc||prior.cc||[],bcc:v.bcc||prior.bcc||[],attachments,status:'draft',scheduledAt:null,actionId:null,bodyHtml:null};
  delete d.addAttachments;delete d.removeAttachmentIds;delete d.version;delete d.force;delete d.fromEmail;
  if(d.mode!=='new'){
    if(!d.threadId)throw new AppError('validation_failed','Choose the conversation to reply to.',422);const thread=await resource(ctx,d.threadId,'thread');if(thread.connectionId!==c.id)throw new AppError('validation_failed','A reply must use the conversation’s Google account.',422);
    const detail=ctx.workspace.demo?object(thread.data):object((await hydrateThread(c,thread.providerId)).data);const messages=(detail.messages||[]) as any[];const m=d.inReplyToMessageId?messages.find(m=>m.id===d.inReplyToMessageId):messages.at(-1);if(!m)throw new AppError('not_found','The message being answered was not found.',404);
    d.inReplyToMessageId=m.id;d._providerThreadId=thread.providerId;
    if(d.mode!=='forward'){const bare=(s:string)=>s.replace(/^(?:(?:re|fwd?)\s*:\s*)+/gi,'').trim().toLowerCase();if(bare(d.subject)!==bare(String(detail.subject||m.subject||'')))throw new AppError('validation_failed','A threaded reply must preserve the original subject. Use a new message to change it.',422);d._inReplyTo=m._messageId||m.messageId;d._references=[...(m._references||m.references||[]),d._inReplyTo].filter(Boolean);}
    if(v.includeOriginalAttachments){for(const a of m.attachments||[]){let bytes=a.dataBase64;if(!bytes&&a.attachmentId&&!ctx.workspace.demo)bytes=(await api(c,`gmail/messages/${enc(m.id)}/attachments/${enc(a.attachmentId)}`)).data;if(bytes)attachments.push({...a,id:randomUUID(),dataBase64:Buffer.from(bytes,'base64url').toString('base64')});}}
  }
  if(attachments.reduce((n,a)=>n+a.size,0)>10_000_000)throw new AppError('too_large','Attachments are limited to 10 MB per message.',413);return d;
}
export async function createDraft(ctx:Context,input:unknown) {
  const v=V.draftCreate.parse(input),c=await connection(ctx,v.accountId);assertScope(c,'mail',ctx);const d=await draftData(ctx,c,v);const raw=await mime(c,d);d._raw=raw;
  if(ctx.workspace.demo)return views.draftView(await put(c,'draft',randomUUID(),d,d.threadId||undefined,sha256(raw)));
  const gd=await api(c,'gmail/drafts',{method:'POST',body:JSON.stringify({message:{raw,...(d.mode!=='new'&&d.mode!=='forward'?{threadId:d._providerThreadId}:{})}})});await put(c,'draft',gd.id,d,d.threadId||undefined,sha256(raw));return views.draftView(await hydrateDraft(c,gd.id));
}
export async function updateDraft(ctx:Context,id:string,input:unknown) {
  const v=V.draftUpdate.parse(input);let r=await resource(ctx,id,'draft');const c=await connection(ctx,r.connectionId);assertScope(c,'mail',ctx);if(!ctx.workspace.demo)r=await hydrateDraft(c,r.providerId);
  if(v.version!==(r.version||r.updatedAt.toISOString())&&!v.force)throw new AppError('conflict','This draft changed. Refresh it before saving.',409);
  const claimed=await db.action.count({where:{workspaceId:ctx.workspace.id,status:'running',payload:{path:['input','draftId'],equals:id}}});if(claimed)throw new AppError('conflict','This draft is being sent. Wait for its result.',409);
  await db.action.updateMany({where:{workspaceId:ctx.workspace.id,status:{in:['proposed','approved','queued']},payload:{path:['input','draftId'],equals:id}},data:{status:'needs_review',error:'The draft changed after its send was prepared.'}});
  const d=await draftData(ctx,c,v,object(r.data)),raw=await mime(c,d);d._raw=raw;
  if(!ctx.workspace.demo)await api(c,`gmail/drafts/${enc(r.providerId)}`,{method:'PUT',body:JSON.stringify({id:r.providerId,message:{raw,...(d.mode!=='new'&&d.mode!=='forward'?{threadId:d._providerThreadId}:{})}})});
  r=await put(c,'draft',r.providerId,d,r.parentId||undefined,sha256(raw));return views.draftView(ctx.workspace.demo?r:await hydrateDraft(c,r.providerId));
}
export async function deleteDraft(ctx:Context,id:string) {const r=await resource(ctx,id,'draft'),c=await connection(ctx,r.connectionId);assertScope(c,'mail',ctx);if(await db.action.count({where:{workspaceId:ctx.workspace.id,status:'running',payload:{path:['input','draftId'],equals:id}}}))throw new AppError('conflict','This draft is being sent.',409);if(!ctx.workspace.demo)await api(c,`gmail/drafts/${enc(r.providerId)}`,{method:'DELETE'});await db.action.updateMany({where:{workspaceId:ctx.workspace.id,status:{in:['proposed','approved','queued','needs_review']},payload:{path:['input','draftId'],equals:id}},data:{status:'canceled'}});await db.resource.delete({where:{id}});return {id};}
export function validateWindow(min:string,max:string) {const a=Date.parse(min),b=Date.parse(max);if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a||b-a>62*86400000)throw new AppError('validation_failed','Choose a time range of up to 62 days.',422);return {a,b};}
export async function getEvents(ctx:Context,min:string,max:string,calendarIds?:string[],q?:string) {
  const {a,b}=validateWindow(min,max),gaps:T.SourceGap[]=[];let calendars=await resources(ctx,'calendar');if(calendarIds?.length){for(const id of calendarIds)await resource(ctx,id,'calendar');calendars=calendars.filter(c=>calendarIds.includes(c.id));}else calendars=calendars.filter(c=>views.calendarView(c).visible);
  const seen=new Set<string>(),out:Resource[]=[];
  for(const cal of calendars){if(seen.has(cal.providerId))continue;const c=await connection(ctx,cal.connectionId);try{assertScope(c,'calendar',ctx);const es=ctx.workspace.demo?(await resources(ctx,'event',c.id,cal.id)).filter(r=>{const e=views.eventView(r);const start=e.allDay?fromZonedTime(e.start,views.calendarView(cal).timezone).getTime():Date.parse(e.start),end=e.allDay?fromZonedTime(e.end,views.calendarView(cal).timezone).getTime():Date.parse(e.end);return start<b&&end>a;}):await fetchEvents(c,cal,min,max,q);out.push(...es);seen.add(cal.providerId);}catch(e){gaps.push({accountId:c.id,resource:'calendar',resourceId:cal.id,code:'provider_error',message:(e as Error).message});}}
  return list(out.map(views.eventView).filter(e=>e.status!=='cancelled'&&(!q||e.title.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>a.start.localeCompare(b.start)),gaps);
}
function validateEvent(v:any,timezone:string) {if(v.allDay){V.date.parse(v.start);V.date.parse(v.end);if(v.start>=v.end)throw new AppError('validation_failed','All-day events need an exclusive end date after the start.',422);}else{V.instant.parse(v.start);V.instant.parse(v.end);if(Date.parse(v.end)<=Date.parse(v.start))throw new AppError('validation_failed','End time must be after start time.',422);}V.zone.parse(timezone);}
function eventBody(v:any,timezone:string) {const body:any={};if(v.title!==undefined)body.summary=v.title;if(v.description!==undefined)body.description=v.description||'';if(v.location!==undefined)body.location=v.location||'';
  if(v.start)body.start=v.allDay?{date:v.start}:{dateTime:v.start,timeZone:timezone};if(v.end)body.end=v.allDay?{date:v.end}:{dateTime:v.end,timeZone:timezone};if(v.attendees)body.attendees=v.attendees.map((a:any)=>({email:a.email,displayName:a.name||undefined,optional:a.optional||false}));if(v.recurrence!==undefined)body.recurrence=v.recurrence||[];if(v.reminderMinutes)body.reminders={useDefault:false,overrides:v.reminderMinutes.map((minutes:number)=>({method:'popup',minutes}))};if(v.addMeet)body.conferenceData={createRequest:{requestId:randomUUID(),conferenceSolutionKey:{type:'hangoutsMeet'}}};return body;
}
export async function createEvent(ctx:Context,input:unknown,executionId?:string) {
  const v=V.eventCreate.parse(input),cal=await resource(ctx,v.calendarId,'calendar'),c=await connection(ctx,cal.connectionId),cv=views.calendarView(cal);assertScope(c,'calendar',ctx);if(!['owner','writer'].includes(cv.accessRole))throw new AppError('forbidden','This calendar is read-only.',403);const timezone=v.timezone||cv.timezone;validateEvent(v,timezone);
  const id=executionId?sha256(executionId).slice(0,32):randomUUID().replaceAll('-','');let e:any;
  if(ctx.workspace.demo)e={...v,timezone,status:'confirmed',busy:true,canEdit:true,canRsvp:false,organizer:{email:c.email,name:c.name},attendees:(v.attendees||[]).map(a=>({...a,name:a.name||null,responseStatus:'needsAction',optional:!!a.optional,organizer:false,self:a.email===c.email})),calendarId:cal.id,meetUrl:null};
  else{const body={...eventBody(v,timezone),id};const data=await api(c,`calendar/calendars/${enc(cal.providerId)}/events?conferenceDataVersion=1&sendUpdates=${v.notify===false?'none':'all'}`,{method:'POST',body:JSON.stringify(body)});e=eventData(c,{...cv,providerId:cal.providerId},data);e.version=data.etag;}
  const r=await put(c,'event',id,e,cal.id,e.version||randomUUID());await activity(ctx,'calendar.created','Created event: '+v.title,{},c.id,r.id);return views.eventView(r);
}
export async function updateEvent(ctx:Context,id:string,input:unknown) {const v=V.eventUpdate.parse(input);let r=await resource(ctx,id,'event');const c=await connection(ctx,r.connectionId),cal=await resource(ctx,r.parentId!,'calendar'),cv=views.calendarView(cal);assertScope(c,'calendar',ctx);let current=views.eventView(r);let pid=v.scope==='series'?(object(r.data)._providerSeriesId as string||r.providerId):r.providerId;
  if(!ctx.workspace.demo){const latest=await api(c,`calendar/calendars/${enc(cal.providerId)}/events/${enc(pid)}`);if(v.version&&v.version!==latest.etag&&v.scope!=='series')throw new AppError('conflict','This event changed. Refresh it before editing.',409);r=await put(c,'event',pid,eventData(c,{...cv,providerId:cal.providerId},latest),cal.id,latest.etag);current=views.eventView(r);}
  if(!current.canEdit)throw new AppError('forbidden','This account cannot change the event details.',403);if(ctx.workspace.demo&&v.version&&v.version!==current.version)throw new AppError('conflict','This event changed.',409);const merged={...current,...v};validateEvent(merged,merged.timezone||cv.timezone);
  let d:any;if(ctx.workspace.demo)d=merged;else{const body=eventBody({...v,...(v.start||v.end||v.allDay!==undefined?{start:merged.start,end:merged.end,allDay:merged.allDay}:{})},merged.timezone||cv.timezone);const e=await api(c,`calendar/calendars/${enc(cal.providerId)}/events/${enc(pid)}?conferenceDataVersion=1&sendUpdates=${v.notify===false?'none':'all'}`,{method:'PATCH',body:JSON.stringify(body)},{'If-Match':r.version!});d={...eventData(c,{...cv,providerId:cal.providerId},e),version:e.etag};}
  return views.eventView(await put(c,'event',pid,d,cal.id,d.version||randomUUID()));
}
export async function deleteEvent(ctx:Context,id:string,scope='this',notify=true) {const r=await resource(ctx,id,'event'),c=await connection(ctx,r.connectionId),cal=await resource(ctx,r.parentId!,'calendar');assertScope(c,'calendar',ctx);if(!views.eventView(r).canEdit)throw new AppError('forbidden','This account cannot cancel this event.',403);const pid=scope==='series'?object(r.data)._providerSeriesId as string||r.providerId:r.providerId;if(!ctx.workspace.demo)await api(c,`calendar/calendars/${enc(cal.providerId)}/events/${enc(pid)}?sendUpdates=${notify?'all':'none'}`,{method:'DELETE'},{'If-Match':r.version!});await db.resource.delete({where:{id}});return {id};}
export async function rsvpEvent(ctx:Context,id:string,input:any) {const v=(await import('zod')).z.object({response:(await import('zod')).z.enum(['accepted','tentative','declined']),scope:(await import('zod')).z.enum(['this','series']).optional(),comment:(await import('zod')).z.string().max(1000).optional()}).parse(input);const r=await resource(ctx,id,'event'),c=await connection(ctx,r.connectionId),cal=await resource(ctx,r.parentId!,'calendar');assertScope(c,'calendar',ctx);const ev=views.eventView(r);if(!ev.canRsvp)throw new AppError('forbidden','This account is not an attendee.',403);const pid=v.scope==='series'?object(r.data)._providerSeriesId as string||r.providerId:r.providerId;let d:any={...object(r.data),myResponse:v.response,attendees:ev.attendees.map(a=>a.self?{...a,responseStatus:v.response}:a)};
  if(!ctx.workspace.demo){const latest=await api(c,`calendar/calendars/${enc(cal.providerId)}/events/${enc(pid)}`);const e=await api(c,`calendar/calendars/${enc(cal.providerId)}/events/${enc(pid)}?sendUpdates=all`,{method:'PATCH',body:JSON.stringify({attendees:(latest.attendees||[]).map((a:any)=>a.self?{...a,responseStatus:v.response,comment:v.comment}:a)})},{'If-Match':latest.etag});d={...eventData(c,{...views.calendarView(cal),providerId:cal.providerId},e),version:e.etag};}return views.eventView(await put(c,'event',pid,d,cal.id,d.version||randomUUID()));
}
export async function availability(ctx:Context,input:any):Promise<T.AvailabilityResult> {
  const {z}=await import('zod');const v=z.object({timeMin:V.instant,timeMax:V.instant,durationMinutes:z.number().int().min(5).max(480),calendarIds:z.array(V.id).max(100).optional(),withinWorkingHours:z.boolean().optional(),limit:z.number().int().min(1).max(50).default(12)}).parse(input);const {a,b}=validateWindow(v.timeMin,v.timeMax),settings=views.settingsView(ctx),busy:T.BusyInterval[]=[],gaps:T.SourceGap[]=[];let cals=await resources(ctx,'calendar');if(v.calendarIds?.length){for(const id of v.calendarIds)await resource(ctx,id,'calendar');cals=cals.filter(c=>v.calendarIds!.includes(c.id));}else cals=cals.filter(c=>views.calendarView(c).includeInAvailability);const seen=new Set<string>(),checked:string[]=[];
  for(const cal of cals){if(seen.has(cal.providerId))continue;const c=await connection(ctx,cal.connectionId);try{assertScope(c,'calendar',ctx);if(ctx.workspace.demo){const es=await getEvents(ctx,v.timeMin,v.timeMax,[cal.id]);for(const e of es.items){if(!e.busy||e.myResponse==='declined')continue;busy.push({calendarId:cal.id,start:e.allDay?fromZonedTime(e.start,settings.timezone).toISOString():e.start,end:e.allDay?fromZonedTime(e.end,settings.timezone).toISOString():e.end});}}else{const f=await api(c,'calendar/freeBusy',{method:'POST',body:JSON.stringify({timeMin:v.timeMin,timeMax:v.timeMax,timeZone:settings.timezone,items:[{id:cal.providerId}]})});const data=f.calendars?.[cal.providerId];if(!data||data.errors?.length)throw new AppError('permission_missing','Google could not read this calendar’s free/busy data.',403);busy.push(...(data.busy||[]).map((x:any)=>({...x,calendarId:cal.id})));}seen.add(cal.providerId);checked.push(cal.id);}catch(e){gaps.push({accountId:c.id,resource:'calendar',resourceId:cal.id,code:'provider_error',message:(e as Error).message});}}
  if(!cals.length)throw new AppError('validation_failed','Select at least one calendar to check.',422);
  const slots:T.TimeSlot[]=[],dur=v.durationMinutes*60000,buffer=settings.meetingBufferMinutes*60000;
  for(let start=Math.ceil(a/900000)*900000;start+dur<=b&&slots.length<v.limit;start+=900000){const end=start+dur;const day=Number(formatInTimeZone(start,settings.timezone,'i'))%7,clock=formatInTimeZone(start,settings.timezone,'HH:mm'),endClock=formatInTimeZone(end,settings.timezone,'HH:mm');if(v.withinWorkingHours!==false&&(!settings.workingHours.days.includes(day)||clock<settings.workingHours.start||endClock>settings.workingHours.end||formatInTimeZone(start,settings.timezone,'yyyy-MM-dd')!==formatInTimeZone(end,settings.timezone,'yyyy-MM-dd')))continue;if(busy.some(x=>start<Date.parse(x.end)+buffer&&end>Date.parse(x.start)-buffer))continue;slots.push({start:new Date(start).toISOString(),end:new Date(end).toISOString()});}
  return {slots,busy,complete:gaps.length===0,gaps,timezone:settings.timezone,calendarIds:checked,checkedAt:new Date().toISOString()};
}
export async function createTask(ctx:Context,input:unknown) {const v=V.taskCreate.parse(input),l=await resource(ctx,v.taskListId,'taskList'),c=await connection(ctx,l.connectionId);assertScope(c,'tasks',ctx);if(v.source){const src=await resource(ctx,v.source.id);v.source=views.sourceView(src);}let parent:Resource|undefined;if(v.parentId){parent=await resource(ctx,v.parentId,'task');if(parent.parentId!==l.id)throw new AppError('validation_failed','Subtasks must be in their parent’s list.',422);}let pid=randomUUID(),data:any={...v,completed:false,completedAt:null,position:String(Date.now()),assigned:false};
  if(!ctx.workspace.demo){const g=await api(c,`tasks/lists/${enc(l.providerId)}/tasks${parent?'?parent='+enc(parent.providerId):''}`,{method:'POST',body:JSON.stringify({title:v.title,notes:(v.notes||'')+(v.source?.url?'\n\nSource: '+v.source.url:''),...(v.due?{due:v.due+'T00:00:00.000Z'}:{})})});pid=g.id;data={...data,position:g.position,url:g.webViewLink||null,version:g.etag};}const r=await put(c,'task',pid,data,l.id,data.version||randomUUID());await activity(ctx,'task.created','Created task: '+v.title,{},c.id,r.id);return views.taskView(r);}
export async function updateTask(ctx:Context,id:string,input:unknown) {const v=V.taskUpdate.parse(input),r=await resource(ctx,id,'task'),c=await connection(ctx,r.connectionId),l=await resource(ctx,r.parentId!,'taskList');assertScope(c,'tasks',ctx);if(v.taskListId&&v.taskListId!==l.id)throw new AppError('validation_failed','Moving a task between lists is not available in this release.',422);let data:any={...object(r.data),...v};if(v.completed!==undefined){data.status=v.completed?'completed':'needsAction';data.completedAt=v.completed?new Date().toISOString():null;}
  if(!ctx.workspace.demo){for(const id of [v.previousId,v.parentId].filter(Boolean) as string[]){const sibling=await resource(ctx,id,'task');if(sibling.parentId!==l.id)throw new AppError('validation_failed','Reordering is limited to this list.',422);}const body:any={};for(const key of ['title','notes'] as const)if(key in v)body[key]=v[key]||'';if(v.due!==undefined)body.due=v.due?v.due+'T00:00:00.000Z':null;if(v.completed!==undefined){body.status=v.completed?'completed':'needsAction';if(!v.completed)body.completed=null;}let g=await api(c,`tasks/lists/${enc(l.providerId)}/tasks/${enc(r.providerId)}`,{method:'PATCH',body:JSON.stringify(body)});if(v.previousId!==undefined||v.parentId!==undefined){let query='';for(const [key,value] of [['parent',v.parentId],['previous',v.previousId]] as const){if(value){const sib=await resource(ctx,value,'task');if(sib.parentId!==l.id)throw new AppError('validation_failed','Reordering is limited to this list.',422);query+=(query?'&':'?')+key+'='+enc(sib.providerId);}}g=await api(c,`tasks/lists/${enc(l.providerId)}/tasks/${enc(r.providerId)}/move${query}`,{method:'POST'});}data={...data,position:g.position,version:g.etag};}return views.taskView(await put(c,'task',r.providerId,data,l.id,data.version||randomUUID()));}
export async function deleteTask(ctx:Context,id:string) {const r=await resource(ctx,id,'task'),c=await connection(ctx,r.connectionId),l=await resource(ctx,r.parentId!,'taskList');assertScope(c,'tasks',ctx);if(!ctx.workspace.demo)await api(c,`tasks/lists/${enc(l.providerId)}/tasks/${enc(r.providerId)}`,{method:'DELETE'});await db.resource.delete({where:{id}});return {id};}
export async function taskListWrite(ctx:Context,input:any,id?:string,remove=false) {let r=id?await resource(ctx,id,'taskList'):null;const c=await connection(ctx,r?.connectionId||V.id.parse(input.accountId));assertScope(c,'tasks',ctx);if(remove){if(views.taskListView(r!).isDefault)throw new AppError('conflict','The default task list cannot be deleted here.',409);if(!ctx.workspace.demo)await api(c,`tasks/users/@me/lists/${enc(r!.providerId)}`,{method:'DELETE'});await db.resource.deleteMany({where:{workspaceId:ctx.workspace.id,parentId:id}});await db.resource.delete({where:{id}});return {id};}const {z}=await import('zod');const title=z.string().min(1).max(1024).parse(input.title);let pid=r?.providerId||randomUUID();if(!ctx.workspace.demo){const g=await api(c,`tasks/users/@me/lists${r?'/'+enc(pid):''}`,{method:r?'PATCH':'POST',body:JSON.stringify({title})});pid=g.id;}return views.taskListView(await put(c,'taskList',pid,{...object(r?.data),title,isDefault:r?!!object(r.data).isDefault:false}));}
export async function getFiles(ctx:Context,q='') {const gaps=await gapList(ctx,'files');if(!ctx.workspace.demo)for(const c of await connections(ctx)){if(!scopeAvailable(c,'files',ctx))continue;try{const query="trashed = false"+(q?" and name contains '"+q.replaceAll('\\','\\\\').replaceAll("'","\\'")+"'":'');const files=await pages(c,`drive/files?q=${enc(query)}&pageSize=100&fields=${enc('nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink,size,shared,owners(displayName,emailAddress))')}`,'files');for(const f of files)await put(c,'file',f.id,{...f,owner:f.owners?.[0]?{name:f.owners[0].displayName||null,email:f.owners[0].emailAddress}:null});if(!q)await db.resource.deleteMany({where:{connectionId:c.id,kind:'file',providerId:{notIn:files.map(f=>f.id)}}});}catch(e){gaps.push({accountId:c.id,resource:'files',resourceId:null,code:'provider_error',message:(e as Error).message});}}const bad=new Set(gaps.map(g=>g.accountId));return list((await resources(ctx,'file')).map(views.fileView).filter(f=>!bad.has(f.accountId)&&(!q||f.name.toLowerCase().includes(q.toLowerCase()))),gaps);}
export async function fileContent(ctx:Context,id:string) {const r=await resource(ctx,id,'file'),c=await connection(ctx,r.connectionId);assertScope(c,'files',ctx);if(ctx.workspace.demo)return String(object(r.data).content||'');const f=views.fileView(r);if(['doc','sheet','slides'].includes(f.kind)){const text=await api(c,`drive/files/${enc(r.providerId)}/export?mimeType=${enc(f.kind==='sheet'?'text/csv':'text/plain')}`);if(typeof text!=='string')throw new AppError('provider_error','The file could not be exported as text.',502);return text.slice(0,100000);}throw new AppError('validation_failed','Text summaries currently support Google Docs, Sheets and Slides.',422);}
export async function fileOperation(ctx:Context,input:any):Promise<T.FileActionResult> {const {z}=await import('zod');const v=z.discriminatedUnion('action',[z.object({action:z.literal('create'),accountId:V.id,kind:z.enum(['doc','sheet','slides']),name:z.string().min(1).max(255)}),z.object({action:z.literal('rename'),fileId:V.id,name:z.string().min(1).max(255)}),z.object({action:z.literal('copy'),fileId:V.id,name:z.string().max(255).optional()}),z.object({action:z.literal('trash'),fileId:V.id}),z.object({action:z.literal('summarize'),fileId:V.id})]).parse(input);const r='fileId'in v?await resource(ctx,v.fileId,'file'):null,c=await connection(ctx,r?.connectionId||('accountId'in v?v.accountId:''));assertScope(c,'files',ctx);let data:any=object(r?.data),pid=r?.providerId||randomUUID();
  if(v.action==='summarize'){const content=await fileContent(ctx,r!.id);const {summarize}=await import('./agent');return {file:views.fileView(r!),summary:await summarize(ctx,content),removedFileId:null};}
  if(v.action==='trash'){if(!ctx.workspace.demo)await api(c,`drive/files/${enc(pid)}`,{method:'PATCH',body:JSON.stringify({trashed:true})});await db.resource.delete({where:{id:r!.id}});return {file:null,summary:null,removedFileId:r!.id};}
  const mimeTypes={doc:'application/vnd.google-apps.document',sheet:'application/vnd.google-apps.spreadsheet',slides:'application/vnd.google-apps.presentation'};
  if(ctx.workspace.demo){if(v.action==='copy')pid=randomUUID();data={...data,name:'name'in v?v.name||'Copy of '+data.name:data.name,mimeType:v.action==='create'?mimeTypes[v.kind]:data.mimeType,modifiedTime:new Date().toISOString()};}
  else{const path=v.action==='create'?'drive/files':v.action==='copy'?`drive/files/${enc(pid)}/copy`:`drive/files/${enc(pid)}`;data=await api(c,path+'?fields='+enc('id,name,mimeType,modifiedTime,webViewLink,size,shared'),{method:v.action==='rename'?'PATCH':'POST',body:JSON.stringify({name:'name'in v?v.name||'Copy of '+data.name:undefined,...(v.action==='create'?{mimeType:mimeTypes[v.kind]}:{})})});pid=data.id;}const file=views.fileView(await put(c,'file',pid,data));await activity(ctx,'file.'+v.action,`${v.action}: ${file.name}`,{},c.id,file.id);return {file,summary:null,removedFileId:null};}
export async function contacts(ctx:Context,q:string) {const map=new Map<string,T.Contact>();for(const r of await resources(ctx,'thread'))for(const m of (object(r.data).messages||[]) as any[])for(const a of [m.from,...(m.to||[]),...(m.cc||[])])if(a?.email&&(`${a.name} ${a.email}`).toLowerCase().includes(q.toLowerCase()))map.set(r.connectionId+':'+a.email,{id:sha256(r.connectionId+':'+a.email),accountId:r.connectionId,name:a.name||null,email:a.email,photoUrl:null,origin:'recent'});
  if(views.settingsView(ctx).contactLookup&&!ctx.workspace.demo)for(const c of await connections(ctx)){if(!scopeAvailable(c,'contacts',ctx))continue;const result=await api(c,`people/people:searchContacts?query=${enc(q)}&readMask=names,emailAddresses,photos&pageSize=25`);for(const x of result.results||[]){const p=x.person;for(const e of p.emailAddresses||[])map.set(c.id+':'+e.value,{id:sha256(c.id+':'+p.resourceName+e.value),accountId:c.id,name:p.names?.[0]?.displayName||null,email:e.value,photoUrl:p.photos?.[0]?.url||null,origin:'contacts'});}}return list([...map.values()].slice(0,25));}
